# Generated by Django 6.0.4 on 2026-07-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_time', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('fees_pending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.CharField(max_length=100)),
                ('mode_of_class', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20)),
                ('allocated_consultant', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('sheet_type', models.CharField(choices=[('STUDENT', 'Student Details'), ('ATTENDANCE', 'Attendance'), ('COMPLETED', 'Completed Batch')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('consultant', 'sheet_type')},
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=255, null=True)),
                ('col2', models.CharField(blank=True, max_length=255, null=True)),
                ('col3', models.CharField(blank=True, max_length=255, null=True)),
                ('col4', models.CharField(blank=True, max_length=255, null=True)),
                ('col5', models.CharField(blank=True, max_length=255, null=True)),
                ('col6', models.CharField(blank=True, max_length=255, null=True)),
                ('col7', models.CharField(blank=True, max_length=255, null=True)),
                ('col8', models.CharField(blank=True, max_length=255, null=True)),
                ('col9', models.CharField(blank=True, max_length=255, null=True)),
                ('col10', models.CharField(blank=True, max_length=255, null=True)),
                ('col11', models.CharField(blank=True, max_length=255, null=True)),
                ('col12', models.CharField(blank=True, max_length=255, null=True)),
                ('col13', models.CharField(blank=True, max_length=255, null=True)),
                ('col14', models.CharField(blank=True, max_length=255, null=True)),
                ('col15', models.CharField(blank=True, max_length=255, null=True)),
                ('col16', models.CharField(blank=True, max_length=255, null=True)),
                ('col17', models.CharField(blank=True, max_length=255, null=True)),
                ('col18', models.CharField(blank=True, max_length=255, null=True)),
                ('col19', models.CharField(blank=True, max_length=255, null=True)),
                ('col20', models.CharField(blank=True, max_length=255, null=True)),
                ('col21', models.CharField(blank=True, max_length=255, null=True)),
                ('col22', models.CharField(blank=True, max_length=255, null=True)),
                ('col23', models.CharField(blank=True, max_length=255, null=True)),
                ('col24', models.CharField(blank=True, max_length=255, null=True)),
                ('col25', models.CharField(blank=True, max_length=255, null=True)),
                ('col26', models.CharField(blank=True, max_length=255, null=True)),
                ('col27', models.CharField(blank=True, max_length=255, null=True)),
                ('col28', models.CharField(blank=True, max_length=255, null=True)),
                ('col29', models.CharField(blank=True, max_length=255, null=True)),
                ('col30', models.CharField(blank=True, max_length=255, null=True)),
                ('col31', models.CharField(blank=True, max_length=255, null=True)),
                ('col32', models.CharField(blank=True, max_length=255, null=True)),
                ('col33', models.CharField(blank=True, max_length=255, null=True)),
                ('col34', models.CharField(blank=True, max_length=255, null=True)),
                ('col35', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='excelapp.consultantsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.student')),
            ],
        ),
    ]
