# Generated by Django 6.0.4 on 2026-07-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('nationality', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('consultant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('student_name', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('consultant', 'Consultant'), ('student', 'Student')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_join', models.DateField()),
                ('program_name', models.CharField(max_length=200)),
                ('consultant_name', models.CharField(max_length=200)),
                ('overall_experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('content_relevance', models.CharField(choices=[('Very Relevant', 'Very Relevant'), ('Somewhat Relevant', 'Somewhat Relevant'), ('Not Relevant', 'Not Relevant')], max_length=50)),
                ('quality_materials', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('trainer_encouragement', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=50)),
                ('mode_of_delivery', models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied')], max_length=50)),
                ('class_started_on_time', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('skill_enhancement', models.CharField(choices=[('Yes, Significantly', 'Yes, Significantly'), ('Yes, to some extent', 'Yes, to some extent'), ('No', 'No')], max_length=50)),
                ('confident_apply_skills', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('recording_uploaded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('tools_helpful', models.CharField(choices=[('Very Helpful', 'Very Helpful'), ('Somewhat Helpful', 'Somewhat Helpful'), ('Not Helpful', 'Not Helpful')], max_length=50)),
                ('duration_sufficient', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('program_pace', models.CharField(choices=[('Too Fast', 'Too Fast'), ('Just Right', 'Just Right'), ('Too Slow', 'Too Slow')], max_length=50)),
                ('improvement_suggestion', models.TextField()),
                ('future_topics', models.TextField()),
                ('recommend_program', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('program_rating', models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], max_length=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('sheet_type', models.CharField(choices=[('STUDENT', 'Student Sheet'), ('ATTENDANCE', 'Attendance Sheet'), ('COMPLETED', 'Completed Sheet')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=255, null=True)),
                ('col2', models.CharField(blank=True, max_length=255, null=True)),
                ('col3', models.CharField(blank=True, max_length=255, null=True)),
                ('col4', models.CharField(blank=True, max_length=255, null=True)),
                ('col5', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounts.sheet')),
            ],
        ),
    ]
